name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run tests in docker container
      run: |
        docker-compose up --exit-code-from test test
